
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import React from "react";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "./(sidebar)/AppSidebar";
import Appbar from "./(appbar)/Appbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <SidebarProvider>
      <AppSidebar />
      <main>
        <Appbar />
 {children}

       
      </main>
    </SidebarProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
