// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function fetchCategoriesAndInsertProducts() {
  // Fetch all categories from the 'product_categories' table
  const categories = await prisma.product_categories.findMany();

  console.log("Fetched categories:", categories);

  // Define the full list of product details with all required fields
  const products = [
    {
      name: "10 * 50 mm Hinges",
      categoryName: "Plain Hinges",
      price: 50.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 45.0,
      monthly_bill_price: 55.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1/2 * 2 Hinges",
      categoryName: "Plain Hinges",
      price: 60.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 55.0,
      monthly_bill_price: 65.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1/2 * 3 Hinges",
      categoryName: "Plain Hinges",
      price: 70.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 65.0,
      monthly_bill_price: 75.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "5/8 * 2 1/2 Hinges",
      categoryName: "Plain Hinges",
      price: 75.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 70.0,
      monthly_bill_price: 80.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "5/8 * 3 Hinges",
      categoryName: "Plain Hinges",
      price: 80.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 75.0,
      monthly_bill_price: 85.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "5/8 * 4 Hinges",
      categoryName: "Plain Hinges",
      price: 85.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 80.0,
      monthly_bill_price: 90.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "3/4 * 3 Hinges",
      categoryName: "Plain Hinges",
      price: 90.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 85.0,
      monthly_bill_price: 95.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "3/4 * 4 Hinges",
      categoryName: "Plain Hinges",
      price: 95.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 90.0,
      monthly_bill_price: 100.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 * 3 Hinges",
      categoryName: "Plain Hinges",
      price: 100.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 95.0,
      monthly_bill_price: 105.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 * 4 Hinges",
      categoryName: "Plain Hinges",
      price: 110.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 100.0,
      monthly_bill_price: 115.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 * 5 Hinges",
      categoryName: "Plain Hinges",
      price: 120.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 110.0,
      monthly_bill_price: 125.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/4 * 3 Hinges",
      categoryName: "Plain Hinges",
      price: 130.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 120.0,
      monthly_bill_price: 135.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/4 * 4 Hinges",
      categoryName: "Plain Hinges",
      price: 140.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 130.0,
      monthly_bill_price: 145.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/4 * 5 Hinges",
      categoryName: "Plain Hinges",
      price: 150.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 140.0,
      monthly_bill_price: 155.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/2 * 3 Hinges",
      categoryName: "Plain Hinges",
      price: 160.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 150.0,
      monthly_bill_price: 165.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/2 * 4 Hinges",
      categoryName: "Plain Hinges",
      price: 170.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 160.0,
      monthly_bill_price: 175.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/2 * 5 Hinges",
      categoryName: "Plain Hinges",
      price: 180.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 170.0,
      monthly_bill_price: 185.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "2 * 4 Hinges",
      categoryName: "Plain Hinges",
      price: 190.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 180.0,
      monthly_bill_price: 195.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "2 * 5 Hinges",
      categoryName: "Plain Hinges",
      price: 200.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 190.0,
      monthly_bill_price: 205.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "2 * 6 Hinges",
      categoryName: "Plain Hinges",
      price: 210.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 200.0,
      monthly_bill_price: 215.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 Inch 2 Pin",
      categoryName: "Design Hinges",
      price: 50.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 45.0,
      monthly_bill_price: 55.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 Inch 3 Pin",
      categoryName: "Design Hinges",
      price: 60.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 55.0,
      monthly_bill_price: 65.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/4 Inch 3 Pin",
      categoryName: "Design Hinges",
      price: 70.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 65.0,
      monthly_bill_price: 75.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/2 Inch 3 Pin",
      categoryName: "Design Hinges",
      price: 75.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 70.0,
      monthly_bill_price: 80.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "2 Inch 2 Pin",
      categoryName: "Design Hinges",
      price: 80.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 75.0,
      monthly_bill_price: 85.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "2 Inch 3 Pin",
      categoryName: "Design Hinges",
      price: 90.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 85.0,
      monthly_bill_price: 95.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/4 Hinges 2 Pin",
      categoryName: "Design Hinges",
      price: 100.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 95.0,
      monthly_bill_price: 105.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
    {
      name: "1 1/2 Hinges 3 Pin",
      categoryName: "Design Hinges",
      price: 110.0,
      gst_rate: 18.0,
      hsn_code: 7308,
      stock_quantity: 1000,
      adinath_price: 100.0,
      monthly_bill_price: 115.0,
      monthly_bill_percentage: 10.0,
      bags: 10,
    },
  ];

  // Insert products
  for (const product of products) {
    const category = categories.find(
      (c: { name: string }) => c.name === product.categoryName
    );
    if (category) {
      await prisma.products.create({
        data: {
          name: product.name,
          price: product.price,
          gst_rate: product.gst_rate,
          hsn_code: product.hsn_code,
          stock_quantity: product.stock_quantity,
          adinath_price: product.adinath_price,
          monthly_bill_price: product.monthly_bill_price,
          monthly_bill_percentage: product.monthly_bill_percentage,
          bags: product.bags,
          product_category_id: category.category_id,
          created_at: new Date(),
        },
      });
      console.log(`Inserted product: ${product.name}`);
    } else {
      console.log(`Category not found for product: ${product.name}`);
    }
  }
}

fetchCategoriesAndInsertProducts()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
